export const TESTEDITCC1_GET_PET_IDS_READ = "TESTEDITCC1_GET_PET_IDS_READ"
export const TESTEDITCC1_GET_PET_IDS_READ_SUCCEEDED =
  "TESTEDITCC1_GET_PET_IDS_READ_SUCCEEDED"
export const TESTEDITCC1_GET_PET_IDS_READ_FAILED =
  "TESTEDITCC1_GET_PET_IDS_READ_FAILED"
export const TESTEDITCC1_GET_GET_MANGO_ID_READ =
  "TESTEDITCC1_GET_GET_MANGO_ID_READ"
export const TESTEDITCC1_GET_GET_MANGO_ID_READ_SUCCEEDED =
  "TESTEDITCC1_GET_GET_MANGO_ID_READ_SUCCEEDED"
export const TESTEDITCC1_GET_GET_MANGO_ID_READ_FAILED =
  "TESTEDITCC1_GET_GET_MANGO_ID_READ_FAILED"
